apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup
spec:
  # Backup the database every day at 2AM
  schedule: "0 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: postgres-backup
            image: postgres:13.2
            imagePullPolicy: Always
            command:
              - /bin/sh
              - '-c'
              - >
                apt update && apt install awscli -y &&
                fname=/var/backups/backup-$(date +"%m-%d-%Y-%H-%M").sql.gz &&
                pg_dump -U $POSTGRES_USER -h $POSTGRES_HOST $POSTGRES_DB | gzip > $fname &&
                aws s3 cp $fname s3://$BUCKET_NAME
            envFrom:
              - configMapRef:
                  name: postgresql-to-bucket
              - secretRef:
                  name: postgresql-to-bucket
          restartPolicy: Never
