apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:13.2
          resources:
            limits:
              memory: '2Gi'
              cpu: '2'
          envFrom:
            - configMapRef:
                name: postgresql-to-bucket
            - secretRef:
                name: postgresql-to-bucket
          ports:
            - containerPort: 5432
              name: postgres-port
