apiVersion: v1
kind: Secret
metadata:
  name: postgresql-to-bucket
type: Opaque
stringData:
  # PGPASSWORD is automatically consumed by pg_dump
  PGPASSWORD: password
  # POSTGRES_PASSWORD is automatically consumed by the postgresql container
  # image on creation to set the initial user password
  POSTGRES_PASSWORD: password

  AWS_ACCESS_KEY_ID: ''
  AWS_SECRET_ACCESS_KEY: ''
  AWS_DEFAULT_REGION: eu-central-1
